name: 'CI'
on:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    if: github.event_name  == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'
      - name: Install NPM
        run: |
          npm ci
      - name: Audit NPM
        run: |
          npm audit --audit-level=high
      - name: Run NPM
        run: |
          npm run all

  commit-dist:
    needs: build
    if: |
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'
      - run: npm ci && npm run build && npm run package

  test:
    if: >
      (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') &&
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'

      - name: Test JUnit test import
        uses: ./
        with:
          check_name: Example JUnit Test Report
          report_paths: '**/surefire-reports/TEST-*.xml'
          include_passed: true
          include_skipped: false
          detailed_summary: true
          summary: '<table><thead><tr><th> Application (src/applications) </th></tr></thead><tbody><tr><td> test </td></tr></tbody></table>'
          job_summary_text: |
            # Test Header for Example Junit Test Report
            
            This is some custom body to show in the summary.
          check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'
          annotate_only: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Test PyTest test import
        uses: ./
        with:
          check_name: Example Pytest Report
          report_paths: test_results/python/report_flaky.xml
          include_passed: true
          detailed_summary: true
          comment: true
          annotate_only: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Test Ungrouped test import
        uses: ./
        with:
          check_name: Example Ungrouped Test Report
          report_paths: test_results/multiple/*.xml
          verbose_summary: false
          include_passed: true
          detailed_summary: false
          group_reports: false
          comment: true

      - name: Test JUnit flaky test import
        uses: ./
        with:
          check_name: Example JUnit Flaky Report
          report_paths: test_results/junit-web-test/expectedRetries.xml
          include_passed: true
          check_retries: true
          job_summary: true
          detailed_summary: true
          flaky_summary: true
          annotate_only: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Test Multi test import
        uses: ./
        with:
          check_name: |-
            Example Multi JUnit Test Report
            Example Multi Pytest Report
          report_paths: |-
            **/surefire-reports/TEST-*.xml
            test_results/python/report.xml
          summary: |-
            <table><thead><tr><th> Application (src/applications) </th></tr></thead><tbody><tr><td> multi test </td></tr></tbody></table>
            Custom Summary
          check_title_template: |-
            {{SUITE_NAME}} | {{TEST_NAME}}
            \n
          transformers: |
            [{"searchValue":"::","replaceValue":"/"}]
          annotate_only: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Test Nested JUnit test import
        uses: ./
        with:
          check_name: Example Nested JUnit Test Report
          report_paths: 'test_results/nested/multi-level.xml'
          include_passed: true
          detailed_summary: true
          group_suite: true
          comment: true
          skip_annotations: true
          check_title_template: '{{TEST_NAME}}'
          annotate_only: ${{ github.event_name == 'workflow_dispatch' }}
